name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-test:
    name: Build and test

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.x'

    - name: Setup .NET Core SDK 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Setup .NET SDK 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test on .NET Core 3.1
      run: dotnet test -c Release -f netcoreapp3.1 --no-build --no-restore -l "console;verbosity=detailed"

    - name: Test on .NET Core 5.0
      run: dotnet test -c Release -f net5.0 --no-build --no-restore -l "console;verbosity=detailed"

    - name: Test on .NET Framework 4.6.1 (Windows only)
      if: matrix.os == 'windows-latest'
      run: dotnet test -c Release -f net461 --no-build --no-restore -l "console;verbosity=detailed"
