name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
 
  publish-to-nuget:
    runs-on: ubuntu-latest  
    steps:

    - uses: actions/checkout@v2
       
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Setup .NET Core 9.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: Build
      working-directory: src/SortCS 
      run: dotnet build --configuration Release /p:Version=${VERSION}

    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
      working-directory: src/SortCS 
    
    - name: PushNuget
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
      working-directory: src/SortCS 
     